let products=[],cart=JSON.parse(localStorage.getItem("sncart")||"[]"),authMode="customer",editingId=null;
const money=n=>"₹"+Number(n).toLocaleString("en-IN");
async function categories(){let a=await(await fetch("/api/categories")).json();cats.innerHTML=a.map((x,i)=>`<button class="${i?"":"active"}" onclick="selectCategory('${x}',this)">${x}</button>`).join("")}
async function loadProducts(cat="All",q=""){products=await(await fetch("/api/products?category="+encodeURIComponent(cat)+"&search="+encodeURIComponent(q))).json();render()}
function render(){results.textContent=products.length+" products";grid.innerHTML=products.map(p=>`<article class="card"><img src="${p.image}" onclick="details(${p.id})"><div class="body"><small>${p.category}</small><h3>${p.name}</h3><div class="rating">★ ${p.rating}/5</div><b>${money(p.price)}</b> <span class="old">${money(p.old_price)}</span><p class="stock">${p.stock>0?p.stock+" left":"Out of stock"}</p><div class="actions"><button onclick="details(${p.id})">View</button><button ${p.stock<1?"disabled":""} onclick="add(${p.id})">Add</button></div></div></article>`).join("")}
function selectCategory(cat,el){document.querySelectorAll(".cats button").forEach(x=>x.classList.remove("active"));el.classList.add("active");loadProducts(cat,search.value)}function searchProducts(){loadProducts("All",search.value)}
function add(id){let p=products.find(x=>x.id===id);let x=cart.find(a=>a.id===id);if(x&&x.qty>=p.stock)return alert("Maximum available stock reached");x?x.qty++:cart.push({id,qty:1});save();alert("Added to cart")}
function save(){localStorage.setItem("sncart",JSON.stringify(cart));count.textContent=cart.reduce((s,x)=>s+x.qty,0)}
async function details(id){let p=await(await fetch("/api/products/"+id)).json();mi.src=p.image;mc.textContent=p.category;mn.textContent=p.name;mr.textContent="★ "+p.rating+" / 5";md.textContent=p.description;mp.textContent=money(p.price);ms.textContent="Stock: "+p.stock;ma.disabled=p.stock<1;ma.onclick=()=>{add(p.id);closeModal()};modal.classList.remove("hide")}
function closeModal(){modal.classList.add("hide")}
async function openCart(){let h="",sum=0;for(let x of cart){let p=products.find(a=>a.id===x.id)||await(await fetch("/api/products/"+x.id)).json();if(x.qty>p.stock)x.qty=p.stock;if(!x.qty)continue;sum+=p.price*x.qty;h+=`<div class="row"><img src="${p.image}"><div class="grow"><b>${p.name}</b><br>${money(p.price)} × ${x.qty}</div><button onclick="change(${p.id},-1)">−</button><button onclick="change(${p.id},1)">+</button></div>`}save();items.innerHTML=h||"<p>Your cart is empty.</p>";total.textContent=money(sum);cartModal.classList.remove("hide")}
function closeCart(){cartModal.classList.add("hide")}function change(id,n){let x=cart.find(a=>a.id===id);if(!x)return;x.qty+=n;if(x.qty<1)cart=cart.filter(a=>a.id!==id);save();openCart()}
async function openCheckout(){if(!cart.length)return alert("Cart is empty");let m=await(await fetch("/api/me")).json();if(m.role!=="customer"){alert("Login with mobile OTP first");showAuth("customer");return}cartModal.classList.add("hide");checkoutModal.classList.remove("hide")}
function closeCheckout(){checkoutModal.classList.add("hide")}
checkoutForm.onsubmit=async e=>{e.preventDefault();let customer={name:cname.value,phone:phone.value,address:address.value,city:city.value,pincode:pincode.value,payment:payment.value};let r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:cart,customer})}),d=await r.json();if(!r.ok)return alert(d.error);alert("Order #"+d.order_id+" placed! Total: "+money(d.total));cart=[];save();closeCheckout();showOrders();loadProducts()}
async function showAuth(mode){authMode=mode;authModal.classList.remove("hide");authForm.innerHTML=mode==="admin"?`<h2>Admin Login</h2><input id="ae" placeholder="Admin email" type="email"><input id="ap" placeholder="Admin password" type="password"><button onclick="adminLogin()">Login as Admin</button><p class="hint">Demo: admin@shopnest.com / admin123</p>`:`<h2>Customer Login</h2><input id="mnmobile" placeholder="10-digit mobile number" maxlength="10"><input id="custname" placeholder="Name (only needed for new users)"><button onclick="sendOtp()">Send OTP</button><div id="otpBox"></div><p class="hint">Development mode: the OTP will be shown after sending.</p>`}
function closeAuth(){authModal.classList.add("hide")}
async function sendOtp(){let mobile=mnmobile.value.trim();let r=await fetch("/api/send-otp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mobile})}),d=await r.json();if(!r.ok)return alert(d.error);otpBox.innerHTML=`<input id="otp" placeholder="Enter 6-digit OTP" maxlength="6"><p class="demootp">Demo OTP: <b>${d.demo_otp}</b></p><button onclick="verifyOtp()">Verify OTP & Login</button>`}
async function verifyOtp(){let r=await fetch("/api/verify-otp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mobile:mnmobile.value.trim(),otp:otp.value.trim(),name:custname.value.trim()})}),d=await r.json();if(!r.ok)return alert(d.error);closeAuth();checkUser()}
async function adminLogin(){let r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:ae.value,password:ap.value})}),d=await r.json();if(!r.ok)return alert(d.error);closeAuth();openAdmin()}
async function logout(){await fetch("/api/logout",{method:"POST"});checkUser()}
async function adminLogout(){await logout();closeAdmin()}
async function checkUser(){let m=await(await fetch("/api/me")).json();userArea.innerHTML=m.role==="admin"?`<button onclick="openAdmin()">⚙ Admin Panel</button>`:m.role==="customer"?`<span>Hi, ${m.name}</span> <button onclick="showOrders()">My Orders</button> <button onclick="logout()">Logout</button>`:`<button onclick="showAuth('customer')">Mobile Login</button> <button onclick="showAuth('admin')">Admin Login</button>`}
async function showOrders(){let r=await fetch("/api/orders");if(r.status===401)return showAuth("customer");let a=await r.json();orders.innerHTML=a.length?a.map(o=>`<div class="order"><b>Order #${o.id}</b><span class="status">${o.status}</span><p>${new Date(o.created_at).toLocaleString()} • ${o.payment_method}</p><p>${o.items.map(i=>`${i.name} × ${i.quantity}`).join(", ")}</p><strong>${money(o.total)}</strong></div>`).join(""):"<p>No orders yet.</p>";ordersModal.classList.remove("hide")}
function closeOrders(){ordersModal.classList.add("hide")}

async function openAdmin(){adminModal.classList.remove("hide");await adminStats();adminSection("products")}
function closeAdmin(){adminModal.classList.add("hide")}
async function adminStats(){let r=await fetch("/api/admin/stats");if(r.status!==200)return;let s=await r.json();sProducts.textContent=s.products;sUsers.textContent=s.users;sOrders.textContent=s.orders;sSales.textContent=money(s.sales)}
async function adminSection(sec){if(sec==="products"){let a=await(await fetch("/api/admin/products")).json();adminContent.innerHTML=`<h3>Products</h3><div class="table">${a.map(p=>`<div class="adminrow"><img src="${p.image}"><div class="grow"><b>${p.name}</b><small>${p.category} • ₹${p.price} • Stock: ${p.stock}</small></div><button onclick='editProduct(${JSON.stringify(p)})'>Edit</button><button class="danger" onclick="deleteProduct(${p.id})">Delete</button></div>`).join("")}</div>`}
if(sec==="add")productForm();if(sec==="orders")adminOrders()}
function productForm(p={}){editingId=p.id||null;adminContent.innerHTML=`<h3>${editingId?"Edit":"Add"} Product</h3><div class="productform"><input id="pn" placeholder="Product name" value="${p.name||""}"><input id="pc" placeholder="Category" value="${p.category||""}"><input id="pp" type="number" placeholder="Price" value="${p.price||""}"><input id="po" type="number" placeholder="Old price" value="${p.old_price||""}"><input id="pr" type="number" step=".1" placeholder="Rating" value="${p.rating||4}"><input id="ps" type="number" placeholder="Stock" value="${p.stock??10}"><input id="pi" placeholder="Product image URL" value="${p.image||""}"><textarea id="pd" placeholder="Description">${p.description||""}</textarea><button onclick="saveProduct()">Save Product</button></div>`}
function editProduct(p){productForm(p)}
async function saveProduct(){let d={name:pn.value,category:pc.value,price:pp.value,old_price:po.value,rating:pr.value,stock:ps.value,image:pi.value,description:pd.value};let url=editingId?"/api/admin/products/"+editingId:"/api/admin/products";let r=await fetch(url,{method:editingId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)}),x=await r.json();if(!r.ok)return alert(x.error);alert("Product saved");await adminStats();adminSection("products");loadProducts()}
async function deleteProduct(id){if(!confirm("Delete this product?"))return;let r=await fetch("/api/admin/products/"+id,{method:"DELETE"}),d=await r.json();if(!r.ok)return alert(d.error);adminSection("products");loadProducts()}
async function adminOrders(){let a=await(await fetch("/api/admin/orders")).json();adminContent.innerHTML=`<h3>All Orders</h3>${a.map(o=>`<div class="adminorder"><div><b>Order #${o.id}</b> • ${o.customer_name} • ${o.mobile}<br><small>${o.address}, ${o.city} - ${o.pincode}</small><p>${o.items.map(i=>`${i.name} × ${i.quantity}`).join(", ")} • <b>${money(o.total)}</b></p></div><select onchange="changeStatus(${o.id},this.value)">${["Placed","Confirmed","Shipped","Delivered","Cancelled"].map(s=>`<option ${s===o.status?"selected":""}>${s}</option>`).join("")}</select></div>`).join("")}`}
async function changeStatus(id,status){let r=await fetch("/api/admin/orders/"+id+"/status",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});let d=await r.json();if(!r.ok)alert(d.error);else{alert("Order status updated");adminStats()}}
categories();loadProducts();save();checkUser();
